use std::{error::Error, fmt::Display, sync::mpsc};

/// The various kinds of errors that can be produced while runing this TUI.
#[derive(Debug)]
pub enum GrapeGuiError {
    /// Errors generated by [`std::fmt`]
    FmtError(std::fmt::Error),
    /// Errors generated by [`std::io`]
    IOError(std::io::Error),
    /// Errors generated when [`mpsc::send`](std::sync::mpsc::Sender::send) fails
    MPSCSendError,
    /// Errors generated when [`mpsc::recv`](std::sync::mpsc::Receiver::recv) fails
    MPSCRecvError(mpsc::RecvError),
    /// Errors generated when [`mpsc::try_recv`](std::sync::mpsc::Receiver::try_recv) fails
    MPSCTryRecvError(mpsc::TryRecvError),
    /// Errors generated when a thread fails to [`join`](std::thread::JoinHandle::join)
    JoinError,
}

impl Display for GrapeGuiError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:#?}", self)
    }
}

impl Error for GrapeGuiError {}

impl From<std::fmt::Error> for GrapeGuiError {
    fn from(value: std::fmt::Error) -> Self {
        Self::FmtError(value)
    }
}

impl From<std::io::Error> for GrapeGuiError {
    fn from(value: std::io::Error) -> Self {
        Self::IOError(value)
    }
}

impl<T> From<mpsc::SendError<T>> for GrapeGuiError {
    fn from(_: mpsc::SendError<T>) -> Self {
        Self::MPSCSendError
    }
}

impl<T> From<mpsc::TrySendError<T>> for GrapeGuiError {
    fn from(_: mpsc::TrySendError<T>) -> Self {
        Self::MPSCSendError
    }
}

impl From<mpsc::RecvError> for GrapeGuiError {
    fn from(value: mpsc::RecvError) -> Self {
        Self::MPSCRecvError(value)
    }
}

impl From<mpsc::TryRecvError> for GrapeGuiError {
    fn from(value: mpsc::TryRecvError) -> Self {
        Self::MPSCTryRecvError(value)
    }
}
