[package]
name = "CyberGrape"
version = "0.1.0"
edition = "2021"

[lib]
name = "cg"

[[bin]]
name = "monitor"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
