[package]
name = "CyberGrape"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "cg"

[[bin]]
name = "monitor"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = "0.11.1"
clap = { version = "4.4.8", features = ["derive"] }
hound = "3.5.1"
rand = "0.8.5"
rayon = "1.8.0"
serde = { version = "1.0.190", features = ["derive"] }
slint = "1.3.0"
tokio = "1.34.0"
tui = "0.19.0"

[build-dependencies]
cmake = "0.1.50"
