name: Documentation
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: "true"

    - name: Build
      run: cargo doc --verbose --no-deps

    - name: Clear Old Docs Directory
      run: rm -rf ./docs

    - name: Create Landing Page
      run: echo "<meta http-equiv=\"refresh\" content=\"0; url=cg\">" > target/doc/index.html

    - name: Create Docs Directory
      run: cp -r target/doc ./docs

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "docs/"

    # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

