name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: "true"
    - name: Build
      run: cargo build --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: target-dir
        path: target/

  test:
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: target-dir
      - name: Test
        run: cargo test --verbose
