name: Rust

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: "true"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Make Documentation
      run: |
        cargo doc --verbose --no-deps
        rm -rf ./docs
        echo "<meta http-equiv=\"refresh\" content=\"0; url=cg\">" > target/doc/index.html
        cp -r target/doc ./docs
    - name: Upload Documentation Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "docs/"

